name: jetwash_mobile
description: Flutter scaffold for JetWash Pro (minimal)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  supabase_flutter: ^1.3.0
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.7
  google_mlkit_text_recognition: ^0.7.0
  flutter_image_compress: ^1.1.0
  path_provider: ^2.0.0
  share_plus: ^6.0.0
  pdf: ^3.10.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
